// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Whisper.DataManager.Models
{
    public partial class Attachment
    {
        public Attachment()
        {
            Message = new HashSet<Message>();
        }

        public int AttachmentId { get; set; }
        public ContentType Content { get; set; }

        public virtual ICollection<Message> Message { get; set; }
    }
}