// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Whisper.DataManager.Models
{
    public partial class Group
    {
        public Group()
        {
            User = new HashSet<User>();
        }

        public int GroupId { get; set; }
        public string Name { get; set; }
        [JsonIgnore]
        public int Owner { get; set; }
        public long ChannelId { get; set; }
        [JsonIgnore]
        public virtual Channel Channel { get; set; }
        [JsonIgnore]
        public virtual User OwnerNavigation { get; set; }
        [JsonIgnore]
        public virtual ICollection<User> User { get; set; }
    }
}