// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Whisper.DataManager.Models
{
    public partial class Message
    {
        public Message()
        {
            Attachment = new HashSet<Attachment>();
        }

        public int MessageId { get; set; }
        public string Content { get; set; }
        public DateTime? SentAt { get; set; }
        public string Checksum { get; set; }
        public int Sender { get; set; }
        public long ChannelId { get; set; }

        public virtual Channel Channel { get; set; }
        public virtual User SenderNavigation { get; set; }

        public virtual ICollection<Attachment> Attachment { get; set; }
    }
}