// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataManager.Models
{
    public partial class UserMessages
    {
        public string User { get; set; }
        public string Message { get; set; }
    }
}